remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: SixtyForty
description: Simple portfolio rebalancing
logo: /assets/img/small.png
google_analytics: G-5C8N651793

kramdown:
   toc_levels: 2..3

